# Generated by Django 4.1.2 on 2022-11-09 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Post_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Notification_ID', models.IntegerField()),
                ('Post_Date', models.DateTimeField(auto_now_add=True)),
                ('Post_Summary', models.CharField(max_length=200, unique=True)),
                ('Post_Content', models.CharField(max_length=400)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IsAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_author', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Comment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment_Title', models.CharField(max_length=50)),
                ('Comment_Content', models.CharField(max_length=300)),
                ('Post_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
